### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by erflaber** [MitjaNemec/SwapStubs#3]
I tried running the script but it fails with "Fatal error". See attachments for more details.

![image](https://github.com/MitjaNemec/SwapStubs/assets/78447645/8541d113-5f22-4071-9f0b-db537c086b93)
[swap_stubs.log](https://github.com/user-attachments/files/15873791/swap_stubs.log)

**Comment by MitjaNemec** [comment]
Hmmm,

without looking at the schematics the best I can do is guess.

So I think that you don't have any labels on your schematics, this the plugin does not find them and crashes.

Can you also share the schematics or just show relevant screenshot?

**Comment by erflaber** [comment]
I do have global labels in hierarchical sheets and in the main sheet. Is that not supported? Do you still need me to share the schematics?

**Comment by MitjaNemec** [comment]
Aha, that is some additional info that is usefull. Label type should not cause an issue, but I'll have to test is as I tested it only with local labels. Let me check and I'll come back to you.

**Comment by MitjaNemec** [comment]
@erflaber You were right. the plugin did not support the hierarchical and global label type.

I've added support for this in version 1.0.7. Until it becomes available in PCM, you can install it from file available at: https://github.com/MitjaNemec/SwapStubs/releases/tag/1.0.7

**Comment by erflaber** [comment]
Splendid, thank you.
